services:

  usm_abills:
    build:
      context: ${USERSIDE_BASE_DIR}/usm_abills
    volumes:
      - ${USERSIDE_BASE_DIR}/usm_abills/module:/app
      - ${USERSIDE_BASE_DIR}/usm_abills/log:/var/log/usm_abills
      - ${USERSIDE_BASE_DIR}/config/datetime.ini:/usr/local/etc/php/conf.d/timezone.ini
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - internal